query BOOKS {
  books {
    ...BookFragment
  }
}

#列表查询返回的数据必须包含特定查询所需的所有数据。如果特定的书籍查询获取列表查询不返回的字段Apollo Client无法从缓存中返回数据。
#下面就是一个对特定book的查询，messages字段就是books列表查询中没有的字段，因此该特定查询Apollo client无法从缓存中返回数据

query BOOK_BY_ID($id: ID!) {
  bookById(id: $id) {
    ...BookFragment
    comments {
      id
      text
    }
    count @client
  }
}

query COMMENT_BY_PAGE($id: ID!, $offset: Int, $limit: Int, $skip: Boolean!) {
  commentsByPage(id: $id, offset: $offset, limit: $limit) @skip(if: $skip) {
    id
    text
  }
}

query CART {
  cart @client {
    books {
      ...BookFragment
      count
    }
  }
}

query BOOK_DETAIL {
  bookDetail @client {
    comment
  }
}

fragment BookFragment on Book {
  id
  title
  author
}
