mutation singleUpload($file: Upload!) {
  singleUpload(file: $file) {
    id
    filename
  }
}

mutation multipleUpload($files: [Upload!]!) {
  multipleUpload(files: $files) {
    id
    filename
  }
}
