query getTopicById($id: ID!) {
  topic(id: $id) {
    id
    title
    content
    create_at
    visit_count
    tab
    author {
      id
      loginname
      avatar_url
    }
    replies {
      id
      content
    }
  }
}
